//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT_WebThoiTrang.Scripts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryLog
    {
        public int LogID { get; set; }
        public Nullable<int> ProductStockID { get; set; }
        public Nullable<long> QuantityAdded { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ProductStock ProductStock { get; set; }
    }
}
