//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT_WebThoiTrang.Scripts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPromotion
    {
        public int ProductPromotionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PromotionID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
