//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT_WebThoiTrang.Scripts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> StockType { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
